logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql: TRACE
            springframework:
                web: DEBUG
                web.client.RestTemplate: DEBUG
                ws:
                    client:
                        MessageTracing:
                            received: TRACE
                            sent: DEBUG
                    server:
                        MessageTracing:
                            received: TRACE
                            sent: DEBUG
spring:
    jpa:
        show-sql: true
